### ISSUE TITLE
feat: load local config file inside a sub directory

### ISSUE THREAD

**Issue by pysan3** [klen/nvim-config-local#2]
Hi @klen,

Thanks for the awesome plugin :)

I usually put the local config file inside a sub directory like `./.vim/local.vim`.
However, adding this path to config_files will result in an error as follows,

```txt
[config-local]: Unsupported config filetype: "/path/to/pwd/.vim/local.vim"
```

It would be really nice if the plugin could find files inside subdirectories.

This is caused by [line 66 in init.lua](https://github.com/klen/nvim-config-local/blob/156eddb64e25cac4728e8b4c413b1853777cb77f/lua/config-local/init.lua#L66) where `vim.fn.fnamemodify(filename, ":t")` only returns the filename (i.e. `local.vim`) which is not included in the config_files.

A possible fix would be to change the argument from `":t"` to `":~:."` which returns the filename relative to the current directory.
```txt
:h filename-modifiers
	:~	Reduce file name to be relative to the home directory, if
		possible.  File name is unmodified if it is not below the home
		directory.
	:.	Reduce file name to be relative to current directory, if
		possible.  File name is unmodified if it is not below the
		current directory, but on MS-Windows the drive is removed if
		it is the current drive.
		For maximum shortness, use ":~:.".
```

And this change can be done to the following three lines.
![image](https://user-images.githubusercontent.com/41065736/155844633-0ef7ef85-18c1-4dd0-8a68-a049c6c5992f.png)

Best,
pysan3

**Comment by klen** [comment]
@pysan3  This is a good point. I've made the changes. Thank you!

**Comment by pysan3** [comment]
It works really good!!

Thanks ;)
